name: Execute SQL Script

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  execute-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PostgreSQL
      uses: docker://postgres:13
      env:
        POSTGRES_DB: ${{ secrets.DB_NAME }}
        POSTGRES_USER: ${{ secrets.DB_USER }}
        POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Execute SQL Script
      run: |
        psql -h localhost -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f path/to/update-schema.sql
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
