name: Deploy SQL Changes to Database

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  deploy-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MySQL Client
      run: sudo apt-get install mysql-client

    - name: Deploy SQL scripts to the database
      env:
        DB_HOST: 'database-1.czea0ueo0k49.us-east-1.rds.amazonaws.com' # ${{ secrets.DB_HOST }}
        DB_USERNAME: 'admin' #${{ secrets.DB_USERNAME }}
        DB_PASSWORD: 'Admin_3212' # ${{ secrets.DB_PASSWORD }}
        DB_NAME: 'rupesh1' # ${{ secrets.DB_NAME }}
      run: |
        set -e  # Exit if any command fails
        
        # Loop through and execute SQL scripts
        for file in Sql_changes/Rupesh_DB/Sample.Sql.txt ; do
          echo "Running SQL script: $file"
          mysql -h $DB_HOST -u $DB_USERNAME -p$DB_PASSWORD $DB_NAME < $file
        done
